# Site settings
title: Owl & Mouse
email: owlnmouse@gmail.com
url: http://owlandmousemusic.com
description: "Owl & Mouse are a five-piece band from London, writing and performing bittersweet, open-hearted indiepop songs with a folk tinge."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#00588e'

# Footer settings
footer: Owl & Mouse

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/owlandmouseuk
  - title: facebook
    url: https://www.facebook.com/owlandmouseuk

# Build settings
markdown: kramdown
permalink: pretty
